services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Papamen123!
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: maven:3.9.8-amazoncorretto-17
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Papamen123!
      DB_NAME: bookstore
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/src/mymaven
    command:
      - /bin/bash
      - -c
      - |
        cd usr/src/mymaven
        mvn clean spring-boot:run -DskipTests

volumes:
  db-data: